using StudentApi.Models;

namespace StudentApi.DataSimulation
{
    public class StudentDataSimulation
    {

        // Static list of students, acting as an in-memory data store, you can change it later on to retrieve students from Database.
        public static readonly List<Student> StudentsList= new List<Student>
        {
            // Initialize the list with some student objects.
            new Student { Id = 1, Name = "Ali Ahmed", Age = 20, Grade = 20 },
    new Student { Id = 2, Name = "Fadi Khail", Age = 22, Grade = 77 },
    new Student { Id = 3, Name = "Ola Jaber", Age = 21, Grade = 66 },
    new Student { Id = 4, Name = "Alia Maher", Age = 19, Grade = 44 },
    new Student { Id = 5, Name = "Sara Nabil", Age = 23, Grade = 91 },
    new Student { Id = 6, Name = "Youssef Karim", Age = 20, Grade = 55 },
    new Student { Id = 7, Name = "Mona Adel", Age = 21, Grade = 73 },
    new Student { Id = 8, Name = "Rami Tarek", Age = 22, Grade = 82 },
    new Student { Id = 9, Name = "Leila Sami", Age = 19, Grade = 68 },
    new Student { Id = 10, Name = "Hassan Fadi", Age = 24, Grade = 49 },
    new Student { Id = 11, Name = "Nour Hana", Age = 20, Grade = 95 },
    new Student { Id = 12, Name = "Bilal Ziad", Age = 21, Grade = 60 },
    new Student { Id = 13, Name = "Aya Walid", Age = 22, Grade = 78 },
    new Student { Id = 14, Name = "Karim Samir", Age = 23, Grade = 85 },
    new Student { Id = 15, Name = "Lina Omar", Age = 19, Grade = 52 },
    new Student { Id = 16, Name = "Amira Nader", Age = 20, Grade = 74 },
    new Student { Id = 17, Name = "Tariq Fares", Age = 22, Grade = 69 },
    new Student { Id = 18, Name = "Salma Rami", Age = 21, Grade = 83 },
    new Student { Id = 19, Name = "Zainab Adel", Age = 23, Grade = 90 },
    new Student { Id = 20, Name = "Omar Fadi", Age = 20, Grade = 57 },
    new Student { Id = 21, Name = "Rana Sami", Age = 22, Grade = 65 },
    new Student { Id = 22, Name = "Mahmoud Ali", Age = 24, Grade = 72 },
    new Student { Id = 23, Name = "Huda Khalid", Age = 19, Grade = 80 },
    new Student { Id = 24, Name = "Adel Tarek", Age = 21, Grade = 59 },
    new Student { Id = 25, Name = "Mariam Ziad", Age = 22, Grade = 84 },
    new Student { Id = 26, Name = "Nabil Rami", Age = 23, Grade = 76 },
    new Student { Id = 27, Name = "Farah Samir", Age = 20, Grade = 63 },
    new Student { Id = 28, Name = "Oussama Ali", Age = 21, Grade = 89 },
    new Student { Id = 29, Name = "Dana Khalid", Age = 22, Grade = 71 },
    new Student { Id = 30, Name = "Walid Omar", Age = 19, Grade = 55 },
    new Student { Id = 31, Name = "Salim Fares", Age = 20, Grade = 82 },
    new Student { Id = 32, Name = "Lamia Ziad", Age = 21, Grade = 93 },
    new Student { Id = 33, Name = "Rayan Tarek", Age = 22, Grade = 60 },
    new Student { Id = 34, Name = "Yara Samir", Age = 23, Grade = 87 },
    new Student { Id = 35, Name = "Bilal Khalid", Age = 20, Grade = 48 },
    new Student { Id = 36, Name = "Nour Adel", Age = 21, Grade = 79 },
    new Student { Id = 37, Name = "Hassan Omar", Age = 22, Grade = 68 },
    new Student { Id = 38, Name = "Mona Rami", Age = 19, Grade = 75 },
    new Student { Id = 39, Name = "Tarek Fadi", Age = 20, Grade = 81 },
    new Student { Id = 40, Name = "Aya Ali", Age = 21, Grade = 54 },
    new Student { Id = 41, Name = "Karim Ziad", Age = 22, Grade = 86 },
    new Student { Id = 42, Name = "Leila Fares", Age = 23, Grade = 92 },
    new Student { Id = 43, Name = "Omar Samir", Age = 20, Grade = 66 },
    new Student { Id = 44, Name = "Rana Khalid", Age = 21, Grade = 58 },
    new Student { Id = 45, Name = "Nabil Adel", Age = 22, Grade = 90 },
    new Student { Id = 46, Name = "Farah Omar", Age = 19, Grade = 73 },
    new Student { Id = 47, Name = "Youssef Rami", Age = 20, Grade = 67 },
    new Student { Id = 48, Name = "Mariam Samir", Age = 21, Grade = 85 },
    new Student { Id = 49, Name = "Salim Ali", Age = 22, Grade = 61 },
    new Student { Id = 50, Name = "Amira Ziad", Age = 23, Grade = 77 },
    new Student { Id = 51, Name = "Rami Khalid", Age = 20, Grade = 83 },
    new Student { Id = 52, Name = "Lina Fares", Age = 21, Grade = 56 },
    new Student { Id = 53, Name = "Ola Omar", Age = 22, Grade = 70 },
    new Student { Id = 54, Name = "Tariq Samir", Age = 23, Grade = 88 },
    new Student { Id = 55, Name = "Nour Ali", Age = 20, Grade = 62 },
    new Student { Id = 56, Name = "Huda Ziad", Age = 21, Grade = 90 },
    new Student { Id = 57, Name = "Walid Rami", Age = 22, Grade = 59 },
    new Student { Id = 58, Name = "Aya Fadi", Age = 23, Grade = 84 },
    new Student { Id = 59, Name = "Karim Omar", Age = 20, Grade = 69 },
    new Student { Id = 60, Name = "Leila Samir", Age = 21, Grade = 76 },
    new Student { Id = 61, Name = "Omar Khalid", Age = 22, Grade = 82 },
    new Student { Id = 62, Name = "Rana Ziad", Age = 23, Grade = 50 },
    new Student { Id = 63, Name = "Bilal Fares", Age = 20, Grade = 91 },
    new Student { Id = 64, Name = "Mona Ali", Age = 21, Grade = 78 },
    new Student { Id = 65, Name = "Tarek Rami", Age = 22, Grade = 67 },
    new Student { Id = 66, Name = "Farah Samir", Age = 23, Grade = 85 },
    new Student { Id = 67, Name = "Youssef Khalid", Age = 20, Grade = 55 },
    new Student { Id = 68, Name = "Amira Omar", Age = 21, Grade = 72 },
    new Student { Id = 69, Name = "Salim Ziad", Age = 22, Grade = 88 },
    new Student { Id = 70, Name = "Lina Rami", Age = 23, Grade = 63 },
    new Student { Id = 71, Name = "Ola Ali", Age = 20, Grade = 81 },
    new Student { Id = 72, Name = "Tariq Fares", Age = 21, Grade = 74 },
    new Student { Id = 73, Name = "Nour Samir", Age = 22, Grade = 96 },
    new Student { Id = 74, Name = "Hassan Khalid", Age = 23, Grade = 60 },
    new Student { Id = 75, Name = "Rami Omar", Age = 20, Grade = 86 },
    new Student { Id = 76, Name = "Mariam Fadi", Age = 21, Grade = 53 },
    new Student { Id = 77, Name = "Salim Ali", Age = 22, Grade = 79 },
    new Student { Id = 78, Name = "Aya Ziad", Age = 23, Grade = 71 },
    new Student { Id = 79, Name = "Karim Rami", Age = 20, Grade = 84 },
    new Student { Id = 80, Name = "Leila Omar", Age = 21, Grade = 68 },
    new Student { Id = 81, Name = "Omar Samir", Age = 22, Grade = 92 },
    new Student { Id = 82, Name = "Rana Khalid", Age = 23, Grade = 66 },
    new Student { Id = 83, Name = "Bilal Adel", Age = 20, Grade = 80 },
    new Student { Id = 84, Name = "Mona Ali", Age = 21, Grade = 73 },
    new Student { Id = 85, Name = "Tarek Ziad", Age = 22, Grade = 89 },
    new Student { Id = 86, Name = "Farah Rami", Age = 23, Grade = 58 },
    new Student { Id = 87, Name = "Youssef Samir", Age = 20, Grade = 77 },
    new Student { Id = 88, Name = "Amira Khalid", Age = 21, Grade = 65 },
    new Student { Id = 89, Name = "Salim Omar", Age = 22, Grade = 90 },
    new Student { Id = 90, Name = "Lina Fadi", Age = 23, Grade = 61 },
    new Student { Id = 91, Name = "Ola Ziad", Age = 20, Grade = 83 },
    new Student { Id = 92, Name = "Tariq Rami", Age = 21, Grade = 70 },
    new Student { Id = 93, Name = "Nour Samir", Age = 22, Grade = 85 },
    new Student { Id = 94, Name = "Hassan Khalid", Age = 23, Grade = 56 },
    new Student { Id = 95, Name = "Rami Omar", Age = 20, Grade = 91 },
    new Student { Id = 96, Name = "Mariam Fadi", Age = 21, Grade = 69 },
    new Student { Id = 97, Name = "Salim Ali", Age = 22, Grade = 87 },
    new Student { Id = 98, Name = "Aya Ziad", Age = 23, Grade = 62 },
    new Student { Id = 99, Name = "Karim Rami", Age = 20, Grade = 75 },
    new Student { Id = 100, Name = "Leila Omar", Age = 21, Grade = 80 }
        };

    }
}
